/*********************************************************************************************************************
Module Name: Alerts Log 
Module Description: This page lists down all the Alerts generated by the system.
**********************************************************************************************************************
*/
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.UI.HtmlControls;
using RAST.DAL;
using System.Data;
using MySql.Data.MySqlClient;
using System.Configuration;
using System.Text;
using System.Data.SqlClient;

public partial class alerts_log : System.Web.UI.Page
{
    /// <summary>
    /// Page Load Event
    /// </summary>
    /// <remarks>
    /// Connect to the database and list down all alerts
    /// </remarks>
    protected void Page_Load(object sender, EventArgs e)
    {
        if (Session["i_UloginId"] == null)
        {
            Response.Redirect("Default.aspx");
        }


        int intUserId = Convert.ToInt16(Session["i_UloginId"]);
        using (MySqlConnection conn = new MySqlConnection(ConfigurationManager.ConnectionStrings["MySqlConnectionString"].ConnectionString))
        {
            conn.Open();
            AlertLog objAlertLog = new AlertLog();
            objAlertLog.ObjCon = conn;
            objAlertLog.StartDate = DateTime.Now.AddMonths(-1);
            objAlertLog.EndDate = DateTime.Now;
            DataSet dsData = objAlertLog.ReadDataset(intUserId, 0, 0);

            string strTableData = "<table id=\"tblAlertLogs\" class=\"table table-bordered table-striped\">\n";
            strTableData = strTableData + "<thead><tr><th>Site Name</th><th>Hub Id</th><th>Sensor Id</th><th>Date Time</th><th>Alert Type</th></tr></thead>";
            strTableData = strTableData + " <tbody>";

            for (int intRowCtr = 0; intRowCtr < dsData.Tables[0].Rows.Count; intRowCtr++)
            {
                strTableData = strTableData + "<tr>";
                strTableData = strTableData + "<td>" + dsData.Tables[0].Rows[intRowCtr][0].ToString() + "</td>";
                strTableData = strTableData + "<td>" + dsData.Tables[0].Rows[intRowCtr][1].ToString() + "</td>";
                strTableData = strTableData + "<td>" + dsData.Tables[0].Rows[intRowCtr][2].ToString() + "</td>";
                strTableData = strTableData + "<td>" + dsData.Tables[0].Rows[intRowCtr][3].ToString() + "</td>";

                if (dsData.Tables[0].Rows[intRowCtr][4].ToString() == "1")
                {
                    strTableData = strTableData + "<td>Above Minimum Threshold.</td>";
                }
                else
                {
                    strTableData = strTableData + "<td>Above Maximum Threshold.</td>";
                }

                strTableData = strTableData + "</tr>";
            }

            strTableData = strTableData + " </tbody></table>";
            objAlertLog = null;
            dsData = null;

            spTable.InnerHtml = strTableData;



        }
    }
}