/*********************************************************************************************************************
Module Name: Error Log 
Module Description: This page lists down all the internal errors  generated by the system.
**********************************************************************************************************************
*/
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Data;
using MySql.Data.MySqlClient;
using System.Configuration;
using System.Text;
using System.Data;
using System.Data.SqlClient;
using RAST.DAL;

public partial class error_log : System.Web.UI.Page
{
    protected void Page_Load(object sender, EventArgs e)
    {
        
        if (Session["i_UloginId"] == null)
        {
            Response.Redirect("Default.aspx");
        }

        int intUserId = Convert.ToInt16(Session["i_UloginId"]);
        try
        {        
            using (MySqlConnection conn = new MySqlConnection(ConfigurationManager.ConnectionStrings["MySqlConnectionString"].ConnectionString))
            {
                conn.Open();
                DataSet dsData = new DataSet();
                MySqlCommand cmd = new MySqlCommand("p_GetLogExceptions", conn);
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("m_UserId", intUserId);
                MySqlDataAdapter sda = new MySqlDataAdapter(cmd);
                sda.Fill(dsData);

                string strTableData = "<table id=\"tblErrorLogs\" class=\"table table-bordered table-striped\">\n";
                strTableData = strTableData + "<thead><tr><th>Date Time</th><th>Exception Message</th><th>Message Type</th><th>Exception URL</th></tr></thead>";
                strTableData = strTableData + " <tbody>";

                for (int intRowCtr = 0; intRowCtr < dsData.Tables[0].Rows.Count; intRowCtr++)
                {
                    strTableData = strTableData + "<tr>";
                    strTableData = strTableData + "<td>" + dsData.Tables[0].Rows[intRowCtr][0].ToString() + "</td>";
                    strTableData = strTableData + "<td>" + dsData.Tables[0].Rows[intRowCtr][1].ToString() + "</td>";
                    strTableData = strTableData + "<td>" + dsData.Tables[0].Rows[intRowCtr][2].ToString() + "</td>";
                    strTableData = strTableData + "<td>" + dsData.Tables[0].Rows[intRowCtr][3].ToString() + "</td>";
                    strTableData = strTableData + "</tr>";
                }

                strTableData = strTableData + " </tbody></table>";
                cmd = null;
                sda = null;
                conn.Close();

                spTable.InnerHtml = strTableData;
            }


        }
        catch (Exception ex)
        {
            LogExceptions objlog = new LogExceptions();
            using (MySqlConnection MySQLCon = new MySqlConnection(ConfigurationManager.ConnectionStrings["MySqlConnectionString"].ConnectionString))
            {
                string exepurl = Request.Url.ToString();
                MySQLCon.Open();
                objlog.conn = MySQLCon;
                objlog.SaveLogExceptions(ex, exepurl);
            }
        }
    }
}